context:
  version: "2.0.5"
  major_minor: ${{ (version | split('.'))[:2] | join('.') }}
  lua: "5.1"

package:
  name: luajit
  version: ${{ version }}

source:
  url: https://github.com/LuaJIT/LuaJIT/archive/refs/tags/v${{ version }}.zip
  sha256: 2adbe397a5b6b8ab22fa8396507ce852a2495db50e50734b3daa1ffcadd9eeb4

build:
  number: 1000
  prefix_detection:
    ignore_binary_files: true
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make

tests:
  - package_contents:
      bin: 
        - luajit
      include: 
        - luajit-${{ major_minor }}/lua.h
        - luajit-${{ major_minor }}/luajit.h
      lib: 
        - luajit-${{ lua }}
  - script:
      - luajit -v
      - luajit -e "print(package.path)"

about:
  homepage: http://luajit.org/
  license: MIT
  license_file: COPYRIGHT
  summary: Just-In-Time Compiler (JIT) for the Lua programming language.

extra:
  recipe-maintainers:
    - brisk022
    - marcelotrevisani
    - baszalmstra
