context:
  name: luajit
  version: "2.0.5"
  version_under: ${{ version | replace("-", "_") }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/LuaJIT/LuaJIT/archive/refs/tags/v${{ version }}.zip
  sha256: 2adbe397a5b6b8ab22fa8396507ce852a2495db50e50734b3daa1ffcadd9eeb4

build:
  number: 1001

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: unix
      then: make
  run_exports: 
    - ${{ pin_subpackage(name) }}
  run_constraints: 
    # Luajit should not be installed together with lua 5.1
    - lua <5.1|>=5.2

tests:
  - package_contents:
      bin: 
        - luajit
      include: 
        - luajit-2.1/lua.h
        - luajit-2.1/luajit.h
      lib: 
        - if: win
          then: lua51
          else: luajit
  - script:
      - luajit -v
      - luajit -e "print(package.path)"

about:
  homepage: http://luajit.org/
  license: MIT
  license_file: COPYRIGHT
  summary: Just-In-Time Compiler (JIT) for the Lua programming language.
  repository: https://github.com/LuaJIT/LuaJIT

extra:
  recipe-maintainers:
    - brisk022
    - marcelotrevisani
    - baszalmstra
